// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/loop.h>
#include <linux/sched.h>

#ifndef __NR_clone3
#define __NR_clone3 435
#endif
#ifndef __NR_close_range
#define __NR_close_range 436
#endif
#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

#define MAX_CLONE_ARGS_BYTES 256
static long syz_clone3(volatile long a0, volatile long a1)
{
  unsigned long copy_size = a1;
  if (copy_size < sizeof(uint64_t) || copy_size > MAX_CLONE_ARGS_BYTES)
    return -1;
  char clone_args[MAX_CLONE_ARGS_BYTES];
  memcpy(&clone_args, (void*)a0, copy_size);
  uint64_t* flags = (uint64_t*)&clone_args;
  *flags &= ~CLONE_VM;
  return handle_clone_ret((long)syscall(__NR_clone3, &clone_args, copy_size));
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0ul,
          /*flags=*/0x200002, /*mode=*/0);
  syscall(__NR_socket, /*domain=*/0xaul, /*type=*/2ul, /*proto=*/0x88);
  syscall(__NR_prlimit64, /*pid=*/0, /*res=RLIMIT_RTPRIO*/ 0xeul, /*new=*/0ul,
          /*old=*/0ul);
  syscall(__NR_connect, /*fd=*/-1, /*addr=*/0ul, /*addrlen=*/0ul);
  *(uint64_t*)0x200000000a00 = 0;
  *(uint64_t*)0x200000000a08 = 0;
  *(uint64_t*)0x200000000a10 = 0;
  *(uint64_t*)0x200000000a18 = 0;
  *(uint32_t*)0x200000000a20 = 0x1d;
  *(uint64_t*)0x200000000a28 = 0;
  *(uint64_t*)0x200000000a30 = 0;
  *(uint64_t*)0x200000000a38 = 0;
  *(uint64_t*)0x200000000a40 = 0;
  *(uint64_t*)0x200000000a48 = 0;
  *(uint32_t*)0x200000000a50 = -1;
  syz_clone3(/*args=*/0x200000000a00, /*size=*/0x58);
  *(uint32_t*)0x20000001d000 = 1;
  *(uint32_t*)0x20000001d004 = 0x70;
  *(uint8_t*)0x20000001d008 = 0;
  *(uint8_t*)0x20000001d009 = 0;
  *(uint8_t*)0x20000001d00a = 0;
  *(uint8_t*)0x20000001d00b = 0;
  *(uint32_t*)0x20000001d00c = 0;
  *(uint64_t*)0x20000001d010 = 0x7f;
  *(uint64_t*)0x20000001d018 = 0;
  *(uint64_t*)0x20000001d020 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0x81, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 38, 26);
  *(uint32_t*)0x20000001d030 = 0;
  *(uint32_t*)0x20000001d034 = 0;
  *(uint64_t*)0x20000001d038 = 0x200000000000;
  *(uint64_t*)0x20000001d040 = 0;
  *(uint64_t*)0x20000001d048 = 0;
  *(uint64_t*)0x20000001d050 = 0;
  *(uint32_t*)0x20000001d058 = 0;
  *(uint32_t*)0x20000001d05c = 0;
  *(uint64_t*)0x20000001d060 = 0;
  *(uint32_t*)0x20000001d068 = 0;
  *(uint16_t*)0x20000001d06c = 0;
  *(uint16_t*)0x20000001d06e = 0;
  *(uint32_t*)0x20000001d070 = 0;
  *(uint32_t*)0x20000001d074 = 0;
  *(uint64_t*)0x20000001d078 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x20000001d000ul, /*pid=*/0,
          /*cpu=*/-1, /*group=*/-1, /*flags=*/0ul);
  res = syscall(__NR_socket, /*domain=*/0xaul, /*type=SOCK_SEQPACKET*/ 5ul,
                /*proto=*/0xa);
  if (res != -1)
    r[0] = res;
  syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0x10);
  res = syscall(
      __NR_open, /*file=*/0ul,
      /*flags=O_TRUNC|O_NONBLOCK|O_NOFOLLOW|O_LARGEFILE|O_CREAT|O_CLOEXEC|0x2*/
      0xa8a42ul, /*mode=*/0ul);
  if (res != -1)
    r[1] = res;
  syscall(__NR_open, /*file=*/0ul, /*flags=O_CREAT*/ 0x40ul, /*mode=*/0ul);
  *(uint32_t*)0x200000000040 = -1;
  *(uint64_t*)0x200000000048 = 9;
  *(uint64_t*)0x200000000050 = 0x180000000;
  *(uint64_t*)0x200000000058 = 0x8000;
  *(uint32_t*)0x200000000060 = 0x1ff;
  *(uint16_t*)0x200000000064 = 5;
  *(uint16_t*)0x200000000066 = 0;
  syscall(__NR_ioctl, /*fd=*/r[1], /*cmd=*/0x40286608,
          /*arg=*/0x200000000040ul);
  syscall(__NR_close_range, /*fd=*/r[0], /*max_fd=*/-1, /*flags=*/0ul);
  syscall(__NR_fchdir, /*fd=*/-1);
  syscall(__NR_setsockopt, /*fd=*/-1, /*level=*/0x10e, /*opt=*/0xc, /*arg=*/0ul,
          /*arglen=*/0ul);
  *(uint32_t*)0x200000045147 = 0;
  *(uint32_t*)0x20000004514b = 0x80;
  *(uint8_t*)0x20000004514f = 1;
  *(uint8_t*)0x200000045150 = 0;
  *(uint8_t*)0x200000045151 = 0;
  *(uint8_t*)0x200000045152 = 0;
  *(uint32_t*)0x200000045153 = 0;
  *(uint64_t*)0x200000045157 = 0;
  *(uint64_t*)0x20000004515f = 0;
  *(uint64_t*)0x200000045167 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 38, 26);
  *(uint32_t*)0x200000045177 = 0;
  *(uint32_t*)0x20000004517b = 0;
  *(uint64_t*)0x20000004517f = 0;
  *(uint64_t*)0x200000045187 = 1;
  *(uint64_t*)0x20000004518f = 0;
  *(uint64_t*)0x200000045197 = 0;
  *(uint32_t*)0x20000004519f = 0;
  *(uint32_t*)0x2000000451a3 = 0;
  *(uint64_t*)0x2000000451a7 = 0;
  *(uint32_t*)0x2000000451af = 0;
  *(uint16_t*)0x2000000451b3 = 0;
  *(uint16_t*)0x2000000451b5 = 0;
  *(uint32_t*)0x2000000451b7 = 0;
  *(uint32_t*)0x2000000451bb = 0;
  *(uint64_t*)0x2000000451bf = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x200000045147ul, /*pid=*/0,
          /*cpu=*/0ul, /*group=*/-1, /*flags=*/0ul);
  memcpy((void*)0x200000000000, "ext4\000", 5);
  memcpy((void*)0x200000000280, "./mnt\000", 6);
  memcpy((void*)0x200000000080, "quota", 5);
  *(uint8_t*)0x200000000085 = 0x2c;
  memcpy((void*)0x200000000086, "stripe", 6);
  *(uint8_t*)0x20000000008c = 0x3d;
  sprintf((char*)0x20000000008d, "0x%016llx", (long long)5);
  *(uint8_t*)0x20000000009f = 0x2c;
  memcpy((void*)0x2000000000a0, "min_batch_time", 14);
  *(uint8_t*)0x2000000000ae = 0x3d;
  sprintf((char*)0x2000000000af, "0x%016llx", (long long)5);
  *(uint8_t*)0x2000000000c1 = 0x2c;
  memcpy((void*)0x2000000000c2, "bh", 2);
  *(uint8_t*)0x2000000000c4 = 0x2c;
  memcpy((void*)0x2000000000c5, "dioread_nolock", 14);
  *(uint8_t*)0x2000000000d3 = 0x2c;
  memcpy((void*)0x2000000000d4, "nombcache", 9);
  *(uint8_t*)0x2000000000dd = 0x2c;
  *(uint8_t*)0x2000000000de = 0;
  memcpy(
      (void*)0x200000000780,
      "\x78\x9c\xec\xdd\x3f\x68\x24\x55\x1c\x07\xf0\xef\xcc\xee\x7a\xe6\x6e\x95"
      "\x53\x1b\x41\xfc\x03\x22\xa2\x81\x70\x76\x82\xcd\xd9\x28\x1c\xc8\x71\x88"
      "\x08\x2a\x9c\x88\xd8\x28\x17\x21\x26\xd8\x25\x82\x60\x63\xa1\xb5\x4a\x2a"
      "\x9b\x20\x76\x46\x4b\x49\x13\x6c\x14\xc1\x2a\x6a\x8a\xd8\x08\x1a\x2c\x0c"
      "\x16\x5a\xac\xcc\x4e\x22\x31\x59\x31\xba\xc9\xce\x91\xf9\x7c\x60\x76\x66"
      "\x76\xdf\x9b\xdf\x1b\x66\xbe\x6f\xb7\x19\x36\x40\x6b\x9d\x4f\x72\x31\x49"
      "\x27\xc9\x74\x92\x5e\x92\x62\x7f\x83\x7b\xea\xe5\xfc\xee\xee\xf2\xd4\xfa"
      "\xd5\x64\x30\x78\xf2\x97\x62\xd8\xae\xde\xaf\xed\xf5\x3b\x97\x64\x29\xc9"
      "\xc3\x49\xd6\xca\x22\x2f\x77\x93\x85\xd5\x67\xb7\x7e\xdb\x78\xfc\xfe\xb7"
      "\xe7\x7b\xf7\x7d\xb8\xfa\xcc\xd4\x44\x4f\x72\xd7\xf6\xd6\xe6\x13\x3b\x1f"
      "\x5c\x7e\xeb\x93\x4b\x0f\x2d\x7c\xf5\xcd\x4f\x97\x8b\x5c\x4c\xff\x6f\xe7"
      "\x75\xfc\x8a\x11\xef\x75\x8b\xe4\xd6\x93\x28\x76\x9d\x28\xba\x4d\x8f\x80"
      "\xa3\xb8\xf2\xfa\xc7\xdf\x56\xb9\xbf\x2d\xc9\xbd\xc3\xfc\xf7\x52\xa6\xbe"
      "\x78\xef\xcc\xdd\xb0\xd6\xcb\x83\xef\xff\x53\xdf\x77\x7f\xfe\xfa\x8e\x49"
      "\x8e\x15\x38\x7e\x83\x41\xaf\xfa\x0e\x5c\x1a\x00\xad\x53\x26\xe9\xa7\x28"
      "\x67\x92\xd4\xdb\x65\x39\x33\x53\xff\x86\xff\xae\x73\xb6\x7c\x65\x76\xee"
      "\xb5\xe9\x97\x66\xe7\xaf\xbd\xd8\xf4\x4c\x05\x1c\x97\x7e\xb2\xf9\xd8\x67"
      "\x67\x3e\x3d\x77\x20\xff\x3f\x76\xea\xfc\x03\xa7\x57\x95\xff\xa7\xae\xac"
      "\x7c\x5f\x6d\xef\x74\x8e\xd0\xe1\xcd\x9b\x4e\x7e\x50\xc0\xc9\xba\xb3\x5e"
      "\x55\xf9\x9f\x7e\x7e\xf1\x81\x1c\x35\xff\xc0\xa9\x21\xff\xd0\x5e\xf2\x0f"
      "\xed\x25\xff\xd0\x5e\xf2\x0f\xed\x25\xff\xd0\x5e\xf2\x0f\xed\x25\xff\xd0"
      "\x5e\xf2\x0f\xed\x25\xff\xd0\x5e\xfb\xf3\x0f\x00\xb4\xcb\xe0\x4c\xd3\x4f"
      "\x20\x03\x4d\x69\x7a\xfe\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x0e\x5b\x9e\x5a\xbf\xba\xb7\x4c\xaa\xe6\x17\xef\x25\xdb\x8f"
      "\x26\xe9\x8e\xaa\xdf\x19\xfe\x1f\x71\x72\xe3\xf0\xf5\xec\xaf\x45\xd5\xec"
      "\x2f\x45\xdd\x6d\x2c\xcf\xdd\x3d\xe6\x01\xc6\xf4\x51\xc3\x4f\x5f\xdf\xfc"
      "\x43\xb3\xf5\xbf\xbc\xab\xd9\xfa\x8b\xd7\x92\xa5\x37\x92\x5c\xe8\x76\x0f"
      "\xdf\x7f\xc5\xee\xfd\xf7\xff\xdd\xf2\x2f\x9f\xf7\x5e\x18\xb3\xc0\x7f\x54"
      "\x1c\xd8\x7f\xe4\xe9\xc9\xd6\x3f\xe8\x8f\x95\x66\xeb\x5f\xda\x48\x3e\xaf"
      "\xe6\x9f\x0b\xa3\xe6\x9f\x32\xb7\x0f\xd7\xa3\xe7\x9f\x7e\x75\xfd\xc6\xac"
      "\xff\xea\xef\x63\x1e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x89\xf9\x33"
      "\x00\x00\xff\xff\x69\xb7\x6d\xd8",
      584);
  syz_mount_image(/*fs=*/0x200000000000, /*dir=*/0x200000000280,
                  /*flags=MS_SYNCHRONOUS*/ 0x10, /*opts=*/0x200000000080,
                  /*chdir=*/-1, /*size=*/0x248, /*img=*/0x200000000780);
  return 0;
}
