// Automatically generated by syz-sysgen; DO NOT EDIT.

package sys

import (
	"embed"

	"github.com/google/syzkaller/sys/generated"

	"github.com/google/syzkaller/sys/darwin"
	"github.com/google/syzkaller/sys/freebsd"
	"github.com/google/syzkaller/sys/fuchsia"
	"github.com/google/syzkaller/sys/linux"
	"github.com/google/syzkaller/sys/netbsd"
	"github.com/google/syzkaller/sys/openbsd"
	"github.com/google/syzkaller/sys/test"
	"github.com/google/syzkaller/sys/trusty"
	"github.com/google/syzkaller/sys/windows"
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	generated.Register("darwin", "amd64", "872bba2ae5409477b673378e8bd7f3c4cb76fb57", darwin.InitTarget, files)
	generated.Register("freebsd", "386", "998df1771bdbed95c1e813657f0303c22863bda9", freebsd.InitTarget, files)
	generated.Register("freebsd", "amd64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "arm64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "riscv64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("fuchsia", "amd64", "964c7fd4b1c8b2f056ea0047c6f157b808eace6d", fuchsia.InitTarget, files)
	generated.Register("fuchsia", "arm64", "aabea56d7a220b467494a72b09e415bcfe2e82a0", fuchsia.InitTarget, files)
	generated.Register("linux", "386", "cc26fa2ea087e7475a785ddac04738e0f1e91acd", linux.InitTarget, files)
	generated.Register("linux", "amd64", "cd586adfd51eb1130dbc908701988720395c5c16", linux.InitTarget, files)
	generated.Register("linux", "arm", "8da0f6258988b0f4cb7c0a939682332040377915", linux.InitTarget, files)
	generated.Register("linux", "arm64", "796095a785372bab0362ddf28a53ed86b5310d55", linux.InitTarget, files)
	generated.Register("linux", "mips64le", "9e8b84e0f21bb117078744b2e104335690afeb68", linux.InitTarget, files)
	generated.Register("linux", "ppc64le", "26b36d6a507146f3136c3ef871130752c2abd6b9", linux.InitTarget, files)
	generated.Register("linux", "riscv64", "c4c60f8e0d2cdbfdb237b6a681023b6707b9e4f8", linux.InitTarget, files)
	generated.Register("linux", "s390x", "8f983913f76d864551d826d4c367e962818590aa", linux.InitTarget, files)
	generated.Register("netbsd", "amd64", "e55c41320cbb764d170d09a2ed5dbe024471a081", netbsd.InitTarget, files)
	generated.Register("openbsd", "amd64", "1ea000ab9607526f7e5426a3893355348153b581", openbsd.InitTarget, files)
	generated.Register("test", "32", "774bd1833e3c8b50f116747de65cf245dbbe7492", test.InitTarget, files)
	generated.Register("test", "32_fork", "b11ab04652e27605ae4a1816ebf7989860974245", test.InitTarget, files)
	generated.Register("test", "64", "3f4c92b9a77e3109f812dc47cdb5d09ecbecd741", test.InitTarget, files)
	generated.Register("test", "64_fork", "0282491ed7d87770001881623ce2ff0bd544caff", test.InitTarget, files)
	generated.Register("test", "64_fuzz", "2fdc070f08aa526d39a3f3e403d6624b1ac963bd", test.InitTarget, files)
	generated.Register("trusty", "arm", "e15883cf9bc294d71c2d4e06d02c4bda0414a94f", trusty.InitTarget, files)
	generated.Register("windows", "amd64", "f14e4fef7483fea72b1b0867de524882897680c6", windows.InitTarget, files)

}
