// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <linux/loop.h>
#include <linux/sched.h>

#ifndef __NR_clone3
#define __NR_clone3 435
#endif
#ifndef __NR_close_range
#define __NR_close_range 436
#endif
#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

#define MAX_CLONE_ARGS_BYTES 256
static long syz_clone3(volatile long a0, volatile long a1)
{
  unsigned long copy_size = a1;
  if (copy_size < sizeof(uint64_t) || copy_size > MAX_CLONE_ARGS_BYTES)
    return -1;
  char clone_args[MAX_CLONE_ARGS_BYTES];
  memcpy(&clone_args, (void*)a0, copy_size);
  uint64_t* flags = (uint64_t*)&clone_args;
  *flags &= ~CLONE_VM;
  return handle_clone_ret((long)syscall(__NR_clone3, &clone_args, copy_size));
}

uint64_t r[7] = {0xffffffffffffffff,
                 0xffffffffffffffff,
                 0xffffffffffffffff,
                 0x0,
                 0xffffffffffffffff,
                 0xffffffffffffffff,
                 0x0};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memcpy((void*)0x200000000040, "./cgroup.cpu/syz0\000", 18);
  syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x200000000040ul,
          /*flags=*/0x200002, /*mode=*/0);
  syscall(__NR_socket, /*domain=*/0xaul, /*type=*/2ul, /*proto=*/0x88);
  *(uint64_t*)0x200000000140 = 8;
  *(uint64_t*)0x200000000148 = 0x8b;
  syscall(__NR_prlimit64, /*pid=*/0, /*res=RLIMIT_RTPRIO*/ 0xeul,
          /*new=*/0x200000000140ul, /*old=*/0ul);
  *(uint64_t*)0x2000000001c0 = 2;
  *(uint64_t*)0x2000000001c8 = 0x10000;
  syscall(__NR_prlimit64, /*pid=*/0, /*res=RLIMIT_RTTIME*/ 0xful,
          /*new=*/0x2000000001c0ul, /*old=*/0ul);
  *(uint32_t*)0x2000000000c0 = 0x28;
  syscall(__NR_setsockopt, /*fd=*/-1, /*level=*/0x11,
          /*optname=UDP_SEGMENT*/ 0x67, /*optval=*/0x2000000000c0ul,
          /*optlen=*/4ul);
  *(uint16_t*)0x200000000000 = 0xa;
  *(uint16_t*)0x200000000002 = htobe16(0x4e21);
  *(uint32_t*)0x200000000004 = htobe32(0);
  memset((void*)0x200000000008, 0, 10);
  memset((void*)0x200000000012, 255, 2);
  *(uint8_t*)0x200000000014 = 0xac;
  *(uint8_t*)0x200000000015 = 0x14;
  *(uint8_t*)0x200000000016 = 0x14;
  *(uint8_t*)0x200000000017 = 0xbb;
  *(uint32_t*)0x200000000018 = 0;
  syscall(__NR_connect, /*fd=*/-1, /*addr=*/0x200000000000ul,
          /*addrlen=*/0x1cul);
  *(uint64_t*)0x200000003cc0 = 0;
  *(uint32_t*)0x200000003cc8 = 0;
  *(uint64_t*)0x200000003cd0 = 0x200000000300;
  *(uint64_t*)0x200000000300 = 0x200000000780;
  memcpy(
      (void*)0x200000000780,
      "\x63\x51\x77\xaf\x0d\xf0\x16\xf3\x91\x65\x93\x42\x2c\x24\x2b\x52\x6b\xab"
      "\x3b\x65\x98\x01\xc1\xc9\xa6\x01\xba\xa2\x40\xf5\x37\x97\x96\x46\xa9\x20"
      "\xd4\xe0\x85\x15\xf5\xfc\xdc\x95\x57\x57\xf8\x8d\xec\xb0\xed\xa6\x4f\xf9"
      "\xcd\x6c\x56\x06\x5a\xd4\x5c\xc2\x7f\x28\xc9\x89\x6c\x7f\x09\x60\x96\x3d"
      "\x25\x5b\x2c\x80\x04\x28\x6c\x5b\xda\xcd\x00\xb0\x19\x79\x6b\x5d\x3a\x79"
      "\x82\xed\x37\x82\x87\xb8\x33\xb3\xc9\x01\xcf\x3d\x64\x12\x87\x7c\xc4\xb4"
      "\xcb\x39\x7f\xcd\x1b\xaf\x23\x3d\x10\xa6\x29\x23\x1f\xd2\xf5\xd9\x4b\x41"
      "\x37\x40\x50\x58\x2d\x04\x30\xa3\x83\x2c\x3a\x74\xd2\x29\xf4\x3f\x1e\x20"
      "\xd2\xf1\x06\xa8\x1d\x9a\x37\x2b\xf3\x79\x3f\x43\xc8\xa6\xad\x7e\x9e\xcc"
      "\xea\x39\x24\xc3\xfe\xc4\xd3\x56\x53\x76\x0c\x15\xa2\xfc\x5d\x5f\xff\x1c"
      "\x1f\x58\x28\xee\x22\xab\x2c\xc0\x3b\x8b\x89\x42\x49\x43\xff\x96\x2a\x2c"
      "\x6d\xa8\x63\xcc\x80\x8c\xec\x4e\x17\x83\x48\x4c\xbb\x1f\xc5\xfc\xa2\xf8"
      "\x2d\xd7\x0c\x29\x30\xb6\x02\x21\x69\xb9\x5c\x75\xbc\xd7\x8a\x20\x5a\x04"
      "\x7a\x47\xa9\x57\x2b\x40\xee\xaa\xd1\xae\xe3\xbd\x07\xb3\xe3\x06\x94\x29"
      "\x1e\x9f\xc4\xb3\x21\x25\xe2\x63\x2c\x74\xcd\xbd\x1a\x3f\x07\x62\xa5\x9c"
      "\x53\x74\x49\xbd\x52\x87\x72\xef\x8c\xd4\x98\x1e\xa7\x9f\xf4\x3b\x20\xbb"
      "\x36\x69\xec\xff\x33\x08\xff\xf2\x79\x67\xef\xcd\xe2\x96\xda\x97\x7c\x92"
      "\x09\xd5\x49\x86\xeb\x4d\xfe\x35\xb4\xe3\x62\xd8\xa3\xfb\x9c\x7f\x0c\xcd"
      "\x73\x4b\x9a\xbf\x9f\xe0\x93\x19\xc2\x15\xf8\x74\x49\x0f\xb3\xce\x6f\xc2"
      "\x7a\xdf\x7d\x39\x79\x15\xf2\xd3\x03\x70\x04\xb6\x1e\xd3\x85\x99\x5b\x00"
      "\xd8\x62\xd2\x6d\x4d\x8b\x6c\x6c\xc2\x7b\x9a\xf0\xd9\xe3\xe3\x90\xb1\xc9"
      "\x1b\xcb\xbc\xbc\x60\x6e\x8f\x51\x5c\xc3\x77\xcc\x6d\xf7\xa0\x87\x52\x25"
      "\xce\xa3\xa2\x9e\x6a\x04\x41\xe5\xe5\x08\xea\xa6\x99\x97\xe8\xf5\xfb\x5b"
      "\xca\xc6\x1e\xc0\x5b\x93\xce\xde\x12\xcb\x34\xd7\x40\x33\x54\x7c\xb2\x5a"
      "\x66\x1f\x65\x1d\x49\x04\xcf\x3f\x12\xc7\x3d\x02\x2d\xa5\x2c\xdf\x15\x28"
      "\x6b\xbf\xf4\xc5\x59\x2e\x93\xc1\x45\x94\xff\xc0\xdb\x4a\x79\x91\x49\x84"
      "\xdc\x82\xb6\x92\x2b\xbe\x51\xa9\x6e\x9c\xce\x44\xfa\x8f\x0f\x7a\xbd\x73"
      "\x7c\x5b\x65\x78\xde\x64\xba\x74\xfc\x82\x3f\x65\xc2\x56\x70\x4b\x6c\xb6"
      "\x91\x81\x56\x26\x51\x21\x88\xd4\x74\x2d\x72\x2b\xc3\x1c\xb0\x7b\xcf\x60"
      "\x82\x8f\x8c\x7b\x81\x7c\xc3\xa1\x79\x37\xd7\xee\x5a\xe1\xf2\xfe\x47\x01"
      "\x5c\x9b\x7b\x2f\xed\x63\xad\x98\x9f\xdc\xb3\x29\xe7\x7c\xcc\x45\xa7\x55"
      "\xf5\x52\xd5\x31\xa0\x89\xf3\xc8\xc1\x7e\xf3\x4f\xcc\xcb\x7f\xa6\x25\xba"
      "\x0f\xbd\x4a\x1c\x5a\xc8\xe0\x6d\x60\xfe\xed\xa8\x7f\x5b\x6d\xb3\x39\x9e"
      "\x50\xae\xf4\x4e\x02\xf4\x65\xfc\xa3\x7b\x5b\x89\x3f\x5c\xc6\xc1\xbf\xc0"
      "\xbe\x85\xb5\x0b\x44\x11\x7c\xa5\x3a\x1e\x25\x6f\x1b\x3f\x1b\xb7\xd4\x46"
      "\x63\x02\x02\x92\x04\x12\x62\x85\x22\x02\xb2\x6b\x9b\x6f\xd0\x5f\xf8\xd9"
      "\x8c\x8d\x5e\x72\x23\xb4\x49\x4d\x1f\x7d\xf7\xab\xbd\x44\x38\xc3\xfd\xfa"
      "\x5b\xaf\xe8\x4e\xcc\x6b\x27\xd6\x84\x4b\x46\x7c\x46\x10\x01\xc5\x17\xec"
      "\x1d\x67\xb7\xa5\x93\x1f\x70\x74\x0d\x39\x3b\x4c\x45\xb7\xc4\x77\xb5\xdc"
      "\x35\xe5\x0e\x30\x20\x34\x5a\xad\x16\x57\xbb\xd7\x7c\x08\x3c\xad\x72\x47"
      "\x8f\x38\x65\x7b\x65\x1d\xe8\x79\x01\x88\x9b\x90\xd5\x37\x01\x2c\xa3\xa7"
      "\x96\x7a\x28\x60\xae\xf0\x06\xfe\xe8\x45\xe9\x8d\xbc\xa1\x35\x01\x37\x2c"
      "\x14\xf5\x9f\x70\xd5\xa5\xbb\xa7\x0a\x68\xf2\x9a\x4f\x29\x9e\xe7\x19\x6e"
      "\x10\x40\x0c\xe5\xf7\x62\x3c\xf3\x1e\xe5\x34\x73\x49\x92\x84\xeb\x0b\xd2"
      "\x26\xfb\x21\xbe\x1b\x15\xbd\xca\xbf\xc2\x37\xa3\x64\x44\x97\xbd\xae\x73"
      "\x8a\x33\x4f\x73\x1f\xc4\x7c\xa9\x83\x72\x95\x41\xd4\xe0\x00\xf3\xa6\xfd"
      "\xfc\xaa\x77\x5f\x0b\x31\xa7\x5d\x60\x7d\xe9\x1b\x82\x6d\x96\x76\x23\xab"
      "\xe7\x13\x65\xe0\x6c\x2d\xda\x62\x7b\xc4\x73\xf4\x28\x0b\x48\x43\x0e\x8f"
      "\xd9\x1b\x02\x7c\x23\xc2\x0c\x1d\x33\x6c\x5f\x48\x18\xae\xfe\x89\x1a\x18"
      "\x49\x31\xb0\x4a\x5a\x4e\x2a\xec\xb0\x70\xe1\x5b\xd9\x5c\xd8\x08\x3f\x4f"
      "\xc0\xd4\x38\xdc\x69\xf1\x60\xe7\xa9\x3d\x1c\x9e\x94\xbb\x41\xe5\xf6\xbb"
      "\xad\xf7\x0e\x40\x70\xc1\x4b\xc6\xb0\xe6\xcc\x2c\x4a\x6b\xf7\x58\x04\xd8"
      "\xa4\x91\x14\x1e\xc4\xe0\xc2\x15\x7b\xdb\xa4\xf4\x0d\xc0\x5b\xc3\x4a\x7a"
      "\xdb\x0a\xc0\x21\xd7\xbb\x5b\xb2\xf2\xf5\x0e\x68\x3a\x13\xaf\x17\x24\x12"
      "\x02\x21\x48\xf7\x61\xa8\x20\xfa\x17\x3e\x3e\xc8\x20\xd7\xa2\x38\xc4\x9c"
      "\x1c\x02\x99\xeb\xfc\xdd\x47\xd2\x14\x88\x00\x53\xae\x6a\x33\x77\xd6\x6b"
      "\x30\xe5\x8c\x7b\x82\x13\x06\x48\x88\xee\xf3\xe3\xa1\xb3\x53\xdb\x61\x91"
      "\x94\x05\x0b\x27\xc1\xd4\x47\x15\xd8\x10\x23\xbd\xc3\x59\xba\xb4\x47\xe7"
      "\xeb\xe9\xad\x22\x08\x49\xe8\x25\x08\x68\xd3\x33\x0e\x9f\x32\x3d\x58\xde"
      "\x19\x9f\x94\x6b\x90\x21\x7f\xf6\x60\x37\x5c\x08\x47\x14\x25\x1a\xd7\xc2"
      "\x7b\xff\x1c\xf9\xd0\x1e\xb8\x19\x53\x8b\x23\x40\xe6\x11\x9c\x39\x58\xdf"
      "\x58\x60\x71\xf8\x2c\xb6\xc4\xcd\x88\x17\xa9\xcd\x33\x7b\x9c\xd9\x94\xe8"
      "\x98\xab\x80\x5b\x41\xd7\x0c\x2f\x4a\x8b\xdd\x4a\x25\xf6\x84\xb4\x86\xc9"
      "\xbf\xd2\x30\x52\x53\xd9\x6b\x7d\xa3\xfe\x1b\x7a\x6d\xbb\xe4\x93\xde\xeb"
      "\xec\xc7\xb1\xe8\x0d\x63\x74\x41\xcb\xf6\x31\x58\xc6\xd7\xad\xae\x8e\x79"
      "\x91\x32\x18\x81\x52\x2b\x2c\x36\xbd\xe0\x8e\xce\xf7\x2c\x5c\xdf\xd8\x9b"
      "\xae\xd7\x29\x0d\xf6\xfc\xe8\xef\x1c\xb8\x7a\xea\x85\x1c\xda\x3f\xb9\xf9"
      "\x4c\x69\xd5\x47\x0d\x6f\xa7\x03\x3c\x89\xd6\x3a\x9c\x63\x79\xc3\xcb\xa0"
      "\xd5\xc6\x20\x16\x28\xe6\x90\xf3\xfb\x76\x6a\xc7\x3b\x71\x6a\x3c\xa6\xb4"
      "\x29\x87\x97\x25\x24\xfb\x63\xfd\x18\xf0\x59\x10\x17\xca\x55\x7f\x4a\xc5"
      "\xed\x0e\xe9\x3b\x7f\x91\x97\xb9\x22\x80\x96\x12\x83\x5b\x02\x96\xb8\x00"
      "\xe3\xfd\x42\xb5\x30\xd3\xf7\xc9\x23\x08\x0d\xa0\xdb\x11\x4a\x58\x58\xe7"
      "\xfa\xd2\x06\xa1\x3f\x46\x74\x06\x8b\x0c\x8d\x8e\xec\x59\xa3\xd1\x89\xda"
      "\xe8\xa1\x95\x02\x40\x69\xfa\x84\x52\x24\xd3\x7a\xb0\x62\x6c\x73\x1a\x98"
      "\x5b\x40\x57\x1b\x28\x30\xfc\x65\x58\x81\x22\x04\xde\xf2\x83\x6f\x75\xd4"
      "\x0b\xdd\xc0\x63\x45\x05\x86\x8c\xbf\xee\x1a\x8b\xb8\x38\x35\x86\x82\x71"
      "\xdf\x14\x86\x63\xc9\x64\x93\x7b\xe0\x63\xb5\xa1\x85\xba\x0d\x40\x60\x94"
      "\x3b\xd1\xdb\xb6\x91\xb4\xcf\x8a\x6a\x91\x1a\x55\x5e\x04\x46\x46\xb5\xa0"
      "\xca\x44\x94\x7f\x94\x68\xf6\xb7\x1e\x02\x3b\x52\x71\xa6\xae\xbd\x2f\x03"
      "\x57\x5a\x95\x6f\x3a\x47\x29\xe1\x44\x75\x35\x71\xf3\x2e\x02\x3d\x36\xb9"
      "\xe0\x35\xd7\xf1\xb0\x01\x9d\xd5\x99\xc3\xac\xe0\x8b\x75\xe2\x5d\x0d\xc8"
      "\x0c\xb3\xfd\x2a\x9b\x9d\x02\x1e\x07\x31\x33\x2b\x48\x53\x06\x87\x99\xfe"
      "\x01\xc6\x16\x80\xd6\x35\x90\x25\x1e\xa5\x8d\x57\xa1\x20\x6c\x4d\xad\xd4"
      "\x11\xf5\x8c\x85\x37\x01\x71\x01\x42\x69\xfc\x3b\xc6\x2a\x9c\x74\x4e\xd4"
      "\x2e\x07\x9b\xd3\xc4\xb4\xc3\xb8\xb7\xa4\xe3\x0f\xac\x06\x07\x26\x0a\xc6"
      "\x41\x95\x8c\x9d\xf5\xb6\x67\xca\xfc\x8e\x12\x26\x58\x3a\xa4\x97\x79\xc7"
      "\x77\x7b\x15\x5f\xd9\xe6\xa9\x3e\x93\x52\x8d\x6d\x83\xe9\xaa\x9b\x32\x22"
      "\x14\xb3\x9a\xec\xc7\x14\x0a\x7a\x5a\x24\x1e\xb0\x1f\x90\xaf\x35\x51\x05"
      "\x79\xaa\xd4\x00\xe0\xd3\xca\x61\x40\x9c\xbd\x16\xc1\xef\x7c\x49\x4e\x69"
      "\x51\x62\x6b\x70\xc9\x58\x6f\xd6\x9b\x30\xdd\x2e\xec\x53\xe9\x6b\x6d\x05"
      "\x82\x7b\x1c\x93\xcc\xb4\x46\xe7\xb8\xda\x67\x21\x7f\xaf\x91\xc3\x60\xf7"
      "\x5a\xca\x87\xb7\x25\xaa\x20\x8c\xbe\x4d\x30\x27\x4a\xa0\x8a\x33\xdc\x15"
      "\x8a\x49\xb9\x44\x3a\xaf\xea\x9f\x53\x02\xc8\xc2\x70\x34\xf4\xf2\x70\xd6"
      "\x67\x35\x97\x2a\x7b\xf0\x87\xdb\x7d\x1b\xd2\xf5\xc5\xb6\x52\x8d\x9f\x7e"
      "\xdb\xe7\x1d\xab\xe6\xb8\xb0\x20\x58\xc5\x1b\x9d\x54\x8d\xd2\x65\x26\x2e"
      "\xf4\xfb\x86\x69\x4c\x81\xbf\xe3\x7c\x3a\xae\x2e\xab\x44\x8c\x0b\xd0\x23"
      "\x34\x1a\xf7\x57\x3e\xdb\x75\xc0\x93\x87\xd2\x8e\xfb\xf3\xfd\x79\xa6\x59"
      "\x61\x04\x7c\xa5\xc4\x32\xfa\x43\xf0\x74\xb8\xfd\x91\x79\x1e\x53\x08\x7a"
      "\xb1\x21\x15\xdc\xec\xbd\xde\xfd\xd8\x1f\xb0\xd0\xe3\x8d\x6e\xde\xab\xef"
      "\x9f\x7a\x0a\xec\xe7\x29\xa1\xbc\xe0\x1f\x98\x8f\x3f\x91\xe6\xd6\x13\xfe"
      "\x22\xf3\xb5\x5d\x4e\x07\x88\x7a\xd3\x42\x0a\xb6\x88\x5e\x8f\x2e\x82\xb2"
      "\x06\x21\xcb\xb4\x04\xec\x9a\x76\x49\x23\x01\x5e\xf3\x62\x34\xa3\xff\xd2"
      "\x81\xc2\x16\x10\x2a\x04\xb4\x03\x85\x74\xb7\x01\xd8\x48\x37\xb6\xb5\xd3"
      "\x30\xb4\x03\x92\x9b\x2e\x10\xf7\x9d\x20\xe1\x8b\x62\xaa\x25\xab\x2b\xfc"
      "\xda\xe5\x23\x73\xe3\x02\x83\x4c\xb4\x72\x6c\x53\x30\xc0\x2c\x2e\x09\x19"
      "\x3e\x65\xcf\xa5\x84\x2a\x33\xa7\xc5\x91\x40\x11\xc2\x62\xf3\x85\x51\xd1"
      "\x0a\xd4\xfd\xe6\xd6\x15\x46\x11\x04\xc4\x5d\x47\x28\x19\xc9\xdf\xa3\xcb"
      "\x9d\xd7\x9a\xdc\x6d\x8c\xbe\xea\x11\x57\x13\x6e\x9a\x24\x03\xc8\x4f\x1c"
      "\x23\x6c\x3c\xbf\xb6\xb9\x2f\x5a\xe3\x0a\x4b\xf2\xf0\xdd\xd3\x86\x1a\x97"
      "\x93\x26\x0b\x9b\xd5\x37\x36\x9f\xf1\xe6\xa6\xdb\x37\xfb\xb1\xdb\xf0\x9b"
      "\xc9\xba\xaa\xd5\x5e\x3c\x0a\xd2\x3b\xcc\x24\xdd\xce\xea\xff\x86\xfb\x1d"
      "\xbf\xa0\xae\x9f\xab\x12\xac\x9c\xdf\xbc\x06\x49\x27\x9c\xd3\x8f\x72\x92"
      "\xe1\x9c\x11\x7f\x07\xb7\xf7\x36\xd8\xa9\x01\x1f\x78\x10\x57\x26\xe8\x58"
      "\x9a\x31\x5c\xf5\x97\x4b\x4e\xdf\xeb\xe0\x3b\x0f\xd8\x91\x06\xba\x7f\x1e"
      "\xdf\x49\xc5\x39\x3d\xb6\xcc\x72\x9f\x84\x19\xed\xe8\xa5\x43\x3d\xbc\x81"
      "\x73\x16\x1c\x29\x25\xe9\x89\x96\x5a\x8e\x01\x6c\x41\x0b\x7c\x9f\xde\x65"
      "\x63\x12\xd8\x25\xc6\x58\x0b\xa6\x0c\x06\xc3\xf7\xf7\x13\x54\x7f\xe8\x6b"
      "\xa5\x71\xd4\xc4\x2b\x12\x4b\xf0\x2e\x51\x77\xd4\x49\xe5\x08\x74\x1b\xfc"
      "\x6a\x79\x8c\xe7\x59\xe6\xa1\x47\x34\x18\x1d\xa8\xe6\x22\x20\xef\x48\x1a"
      "\x62\x93\xc6\xd6\x74\x35\x99\x3c\x3c\x28\xe3\x2e\x39\xe4\xcf\x46\x1f\x06"
      "\x15\xb3\x58\xd1\xb8\x5c\x13\x07\x13\xde\x43\xf7\xb3\x54\xc4\x5c\x4f\xbb"
      "\x9a\x5b\x4b\x65\xf9\x1c\x96\xf5\xa6\xf5\x46\x55\xc9\xd7\xf2\xfc\x19\xa9"
      "\xb2\x6e\x2c\xde\x73\x57\xf3\x2f\x7b\x3a\x33\x5f\xc0\x64\xd1\x06\x94\xcc"
      "\x21\xbe\xf2\xbe\x9c\x19\xee\xa2\x0d\x18\xc5\x51\x10\xcd\x6e\x0c\x71\xa0"
      "\x3b\x60\x7e\x4c\x01\x72\xbd\x54\xe6\xc8\x62\x51\xdd\x01\xa5\xbe\xb2\xd6"
      "\x86\x11\x27\x87\x08\xda\xfd\xa8\xdc\x95\x06\x18\xe2\xae\x27\x88\x2e\x3a"
      "\x35\xe5\xbc\x13\xa2\x77\x62\x1c\x46\xa1\x8f\x50\x93\x6e\x7e\xbe\xc7\x4f"
      "\x80\xfa\x6e\x5f\xb8\xe3\x75\xcc\x6d\x49\xc4\x78\x27\xdc\x07\x95\xbb\x3e"
      "\xdf\x98\x79\xf3\xf7\x78\x92\xeb\xd9\x20\x45\x12\x0f\x30\x0a\x5f\xfa\x52"
      "\x3c\x3e\x02\x5c\x83\x73\x67\xe8\xfb\x59\x7e\x70\xa8\x4e\x07\xe0\xfc\x82"
      "\x18\x31\x41\x07\x9d\xef\xb8\x20\xdd\x87\x0f\x01\xe8\x62\x70\xbd\xb1\x41"
      "\xd1\xd9\xa9\x54\x87\x90\x22\x57\xd1\x29\xfa\x15\x80\x74\x19\x0d\xf0\x40"
      "\x3d\xc6\x69\x7e\x90\x85\x94\x0e\xa0\xba\xcf\xda\x40\x17\x4e\x53\xd1\xf0"
      "\x9e\xbc\xb8\x4b\x99\x24\x77\x99\x78\x87\x1d\x48\x16\x3f\x9c\x9c\x80\x6e"
      "\xf6\xd0\x95\x35\xd6\xd0\x8c\xfc\x93\x29\x6a\xbf\xda\xea\x4f\x04\x98\xd4"
      "\x33\xb9\x7c\x5f\xd6\x59\x30\xab\xbe\x48\xab\x13\xb0\xc4\xba\xca\x64\xef"
      "\x60\x03\xbe\x20\xd0\x02\x66\xd1\x64\xce\xac\x5b\xc9\x77\x0a\xcc\x69\x8d"
      "\x2b\x2a\xa1\x50\x8e\x0e\x69\xd6\x02\x19\xda\xa7\x37\x0d\x45\xe3\xd7\xb5"
      "\x08\x17\x18\xd5\x31\x5f\x12\xcd\xda\x1b\xd1\x17\x32\x04\xb6\xe0\x73\xf3"
      "\x36\xa5\x48\x00\xf2\xbf\x5d\xc3\xd4\xb0\xda\x37\x99\x6d\x26\xda\xe7\x7c"
      "\xd3\xf9\xe8\x8a\xd5\x84\xcf\x30\xf4\xc6\x88\x80\x60\xa3\xef\x7c\x8a\x95"
      "\x14\xed\x24\x47\x3d\xcf\x82\x3d\x9b\x65\xe4\x96\xbd\xb3\xbd\xcf\x2e\x34"
      "\x78\xf6\xa9\x63\x05",
      2561);
  *(uint64_t*)0x200000000308 = 0xa01;
  *(uint64_t*)0x200000003cd8 = 1;
  *(uint64_t*)0x200000003ce0 = 0;
  *(uint64_t*)0x200000003ce8 = 0;
  *(uint32_t*)0x200000003cf0 = 0x20000000;
  *(uint32_t*)0x200000003cf8 = 0xa;
  syscall(__NR_sendmmsg, /*fd=*/-1, /*mmsg=*/0x200000003cc0ul, /*vlen=*/1ul,
          /*f=*/0ul);
  *(uint64_t*)0x200000000a00 = 0;
  *(uint64_t*)0x200000000a08 = 0;
  *(uint64_t*)0x200000000a10 = 0;
  *(uint64_t*)0x200000000a18 = 0;
  *(uint32_t*)0x200000000a20 = 0x1d;
  *(uint64_t*)0x200000000a28 = 0;
  *(uint64_t*)0x200000000a30 = 0;
  *(uint64_t*)0x200000000a38 = 0;
  *(uint64_t*)0x200000000a40 = 0;
  *(uint64_t*)0x200000000a48 = 0;
  *(uint32_t*)0x200000000a50 = -1;
  syz_clone3(/*args=*/0x200000000a00, /*size=*/0x58);
  *(uint32_t*)0x20000001d000 = 1;
  *(uint32_t*)0x20000001d004 = 0x70;
  *(uint8_t*)0x20000001d008 = 0;
  *(uint8_t*)0x20000001d009 = 0;
  *(uint8_t*)0x20000001d00a = 0;
  *(uint8_t*)0x20000001d00b = 0;
  *(uint32_t*)0x20000001d00c = 0;
  *(uint64_t*)0x20000001d010 = 0x7f;
  *(uint64_t*)0x20000001d018 = 0;
  *(uint64_t*)0x20000001d020 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0x81, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 38, 26);
  *(uint32_t*)0x20000001d030 = 0;
  *(uint32_t*)0x20000001d034 = 0;
  *(uint64_t*)0x20000001d038 = 0x200000000000;
  *(uint64_t*)0x20000001d040 = 0;
  *(uint64_t*)0x20000001d048 = 0;
  *(uint64_t*)0x20000001d050 = 0;
  *(uint32_t*)0x20000001d058 = 0;
  *(uint32_t*)0x20000001d05c = 0;
  *(uint64_t*)0x20000001d060 = 0;
  *(uint32_t*)0x20000001d068 = 0;
  *(uint16_t*)0x20000001d06c = 0;
  *(uint16_t*)0x20000001d06e = 0;
  *(uint32_t*)0x20000001d070 = 0;
  *(uint32_t*)0x20000001d074 = 0;
  *(uint64_t*)0x20000001d078 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x20000001d000ul, /*pid=*/0,
          /*cpu=*/-1, /*group=*/-1, /*flags=*/0ul);
  res = syscall(__NR_socket, /*domain=*/0xaul, /*type=SOCK_SEQPACKET*/ 5ul,
                /*proto=*/0xa);
  if (res != -1)
    r[0] = res;
  res = syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0x10);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x200000000100, "./bus\000", 6);
  res = syscall(
      __NR_open, /*file=*/0x200000000100ul,
      /*flags=O_TRUNC|O_NONBLOCK|O_NOFOLLOW|O_LARGEFILE|O_CREAT|O_CLOEXEC|0x2*/
      0xa8a42ul, /*mode=*/0ul);
  if (res != -1)
    r[2] = res;
  syscall(__NR_open, /*file=*/0ul, /*flags=O_CREAT*/ 0x40ul, /*mode=*/0ul);
  *(uint32_t*)0x200000000040 = -1;
  *(uint64_t*)0x200000000048 = 9;
  *(uint64_t*)0x200000000050 = 0x180000000;
  *(uint64_t*)0x200000000058 = 0x8000;
  *(uint32_t*)0x200000000060 = 0x1ff;
  *(uint16_t*)0x200000000064 = 5;
  *(uint16_t*)0x200000000066 = 0;
  syscall(__NR_ioctl, /*fd=*/r[2], /*cmd=*/0x40286608,
          /*arg=*/0x200000000040ul);
  memcpy((void*)0x200000000000,
         "lo\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 16);
  res = syscall(__NR_ioctl, /*fd=*/r[1], /*cmd=*/0x8933,
                /*arg=*/0x200000000000ul);
  if (res != -1)
    r[3] = *(uint32_t*)0x200000000010;
  *(uint16_t*)0x200000000580 = 0x11;
  *(uint16_t*)0x200000000582 = htobe16(0);
  *(uint32_t*)0x200000000584 = r[3];
  *(uint16_t*)0x200000000588 = 1;
  *(uint8_t*)0x20000000058a = 0;
  *(uint8_t*)0x20000000058b = 6;
  memset((void*)0x20000000058c, 255, 6);
  memset((void*)0x200000000592, 0, 2);
  syscall(__NR_bind, /*fd=*/-1, /*addr=*/0x200000000580ul, /*addrlen=*/0x14ul);
  syscall(__NR_close_range, /*fd=*/r[0], /*max_fd=*/-1, /*flags=*/0ul);
  syscall(__NR_fchdir, /*fd=*/-1);
  *(uint32_t*)0x200000000000 = 0xfffffffb;
  *(uint32_t*)0x200000000004 = 0;
  *(uint32_t*)0x200000000008 = 0;
  *(uint32_t*)0x20000000000c = 0;
  syscall(__NR_setsockopt, /*fd=*/-1, /*level=*/0x10e, /*opt=*/0xc,
          /*arg=*/0x200000000000ul, /*arglen=*/0x10ul);
  memcpy((void*)0x200000000140,
         "\x24\x00\x00\x00\x1a\x00\x5f\x02\x14\xf9\xf4\x07\x00\x09\x09\x00\x0a"
         "\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x08\x00\x0f\x00\xff\xff"
         "\xf0\x00",
         36);
  syscall(__NR_write, /*fd=*/-1, /*buf=*/0x200000000140ul, /*count=*/0x24ul);
  memcpy((void*)0x200000000000, "/dev/net/tun\000", 13);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul,
                /*file=*/0x200000000000ul,
                /*flags=__O_TMPFILE|O_TRUNC|O_DIRECT*/ 0x404200, /*mode=*/0);
  if (res != -1)
    r[4] = res;
  memcpy(
      (void*)0x200000000040,
      "\x00\x01\x86\xdd\x06\x10\x00\x08\x01\x6f\x4d\x00\x00\x00\x20\x01\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\xbb\xbb\xbb\xbb\xbb\xbb\xfc\x01\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00",
      52);
  syscall(__NR_write, /*fd=*/r[4], /*buf=*/0x200000000040ul, /*count=*/0x34ul);
  *(uint32_t*)0x200000045147 = 0;
  *(uint32_t*)0x20000004514b = 0x80;
  *(uint8_t*)0x20000004514f = 1;
  *(uint8_t*)0x200000045150 = 0;
  *(uint8_t*)0x200000045151 = 0;
  *(uint8_t*)0x200000045152 = 0;
  *(uint32_t*)0x200000045153 = 0;
  *(uint64_t*)0x200000045157 = 0;
  *(uint64_t*)0x20000004515f = 0;
  *(uint64_t*)0x200000045167 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000004516f, 0, 38, 26);
  *(uint32_t*)0x200000045177 = 0;
  *(uint32_t*)0x20000004517b = 0;
  *(uint64_t*)0x20000004517f = 0;
  *(uint64_t*)0x200000045187 = 1;
  *(uint64_t*)0x20000004518f = 0;
  *(uint64_t*)0x200000045197 = 0;
  *(uint32_t*)0x20000004519f = 0;
  *(uint32_t*)0x2000000451a3 = 0;
  *(uint64_t*)0x2000000451a7 = 0;
  *(uint32_t*)0x2000000451af = 0;
  *(uint16_t*)0x2000000451b3 = 0;
  *(uint16_t*)0x2000000451b5 = 0;
  *(uint32_t*)0x2000000451b7 = 0;
  *(uint32_t*)0x2000000451bb = 0;
  *(uint64_t*)0x2000000451bf = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x200000045147ul, /*pid=*/0,
          /*cpu=*/0ul, /*group=*/-1, /*flags=*/0ul);
  *(uint32_t*)0x20000001d000 = 1;
  *(uint32_t*)0x20000001d004 = 0x70;
  *(uint8_t*)0x20000001d008 = 0;
  *(uint8_t*)0x20000001d009 = 0;
  *(uint8_t*)0x20000001d00a = 0;
  *(uint8_t*)0x20000001d00b = 0;
  *(uint32_t*)0x20000001d00c = 0;
  *(uint64_t*)0x20000001d010 = 0x7f;
  *(uint64_t*)0x20000001d018 = 0;
  *(uint64_t*)0x20000001d020 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0x81, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000001d028, 0, 38, 26);
  *(uint32_t*)0x20000001d030 = 0;
  *(uint32_t*)0x20000001d034 = 0;
  *(uint64_t*)0x20000001d038 = 0x200000000000;
  *(uint64_t*)0x20000001d040 = 0;
  *(uint64_t*)0x20000001d048 = 0;
  *(uint64_t*)0x20000001d050 = 0;
  *(uint32_t*)0x20000001d058 = 0;
  *(uint32_t*)0x20000001d05c = 0;
  *(uint64_t*)0x20000001d060 = 0;
  *(uint32_t*)0x20000001d068 = 0;
  *(uint16_t*)0x20000001d06c = 0;
  *(uint16_t*)0x20000001d06e = 0;
  *(uint32_t*)0x20000001d070 = 0;
  *(uint32_t*)0x20000001d074 = 0;
  *(uint64_t*)0x20000001d078 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x20000001d000ul, /*pid=*/0,
          /*cpu=*/-1, /*group=*/-1, /*flags=*/0ul);
  res = syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0x10);
  if (res != -1)
    r[5] = res;
  memcpy((void*)0x200000000000, "ext4\000", 5);
  memcpy((void*)0x200000000280, "./mnt\000", 6);
  memcpy((void*)0x200000000080, "quota", 5);
  *(uint8_t*)0x200000000085 = 0x2c;
  memcpy((void*)0x200000000086, "stripe", 6);
  *(uint8_t*)0x20000000008c = 0x3d;
  sprintf((char*)0x20000000008d, "0x%016llx", (long long)5);
  *(uint8_t*)0x20000000009f = 0x2c;
  memcpy((void*)0x2000000000a0, "min_batch_time", 14);
  *(uint8_t*)0x2000000000ae = 0x3d;
  sprintf((char*)0x2000000000af, "0x%016llx", (long long)5);
  *(uint8_t*)0x2000000000c1 = 0x2c;
  memcpy((void*)0x2000000000c2, "bh", 2);
  *(uint8_t*)0x2000000000c4 = 0x2c;
  memcpy((void*)0x2000000000c5, "dioread_nolock", 14);
  *(uint8_t*)0x2000000000d3 = 0x2c;
  memcpy((void*)0x2000000000d4, "nombcache", 9);
  *(uint8_t*)0x2000000000dd = 0x2c;
  *(uint8_t*)0x2000000000de = 0;
  memcpy(
      (void*)0x200000000780,
      "\x78\x9c\xec\xdd\x3f\x68\x24\x55\x1c\x07\xf0\xef\xcc\xee\x7a\xe6\x6e\x95"
      "\x53\x1b\x41\xfc\x03\x22\xa2\x81\x70\x76\x82\xcd\xd9\x28\x1c\xc8\x71\x88"
      "\x08\x2a\x9c\x88\xd8\x28\x17\x21\x26\xd8\x25\x82\x60\x63\xa1\xb5\x4a\x2a"
      "\x9b\x20\x76\x46\x4b\x49\x13\x6c\x14\xc1\x2a\x6a\x8a\xd8\x08\x1a\x2c\x0c"
      "\x16\x5a\xac\xcc\x4e\x22\x31\x59\x31\xba\xc9\xce\x91\xf9\x7c\x60\x76\x66"
      "\x76\xdf\x9b\xdf\x1b\x66\xbe\x6f\xb7\x19\x36\x40\x6b\x9d\x4f\x72\x31\x49"
      "\x27\xc9\x74\x92\x5e\x92\x62\x7f\x83\x7b\xea\xe5\xfc\xee\xee\xf2\xd4\xfa"
      "\xd5\x64\x30\x78\xf2\x97\x62\xd8\xae\xde\xaf\xed\xf5\x3b\x97\x64\x29\xc9"
      "\xc3\x49\xd6\xca\x22\x2f\x77\x93\x85\xd5\x67\xb7\x7e\xdb\x78\xfc\xfe\xb7"
      "\xe7\x7b\xf7\x7d\xb8\xfa\xcc\xd4\x44\x4f\x72\xd7\xf6\xd6\xe6\x13\x3b\x1f"
      "\x5c\x7e\xeb\x93\x4b\x0f\x2d\x7c\xf5\xcd\x4f\x97\x8b\x5c\x4c\xff\x6f\xe7"
      "\x75\xfc\x8a\x11\xef\x75\x8b\xe4\xd6\x93\x28\x76\x9d\x28\xba\x4d\x8f\x80"
      "\xa3\xb8\xf2\xfa\xc7\xdf\x56\xb9\xbf\x2d\xc9\xbd\xc3\xfc\xf7\x52\xa6\xbe"
      "\x78\xef\xcc\xdd\xb0\xd6\xcb\x83\xef\xff\x53\xdf\x77\x7f\xfe\xfa\x8e\x49"
      "\x8e\x15\x38\x7e\x83\x41\xaf\xfa\x0e\x5c\x1a\x00\xad\x53\x26\xe9\xa7\x28"
      "\x67\x92\xd4\xdb\x65\x39\x33\x53\xff\x86\xff\xae\x73\xb6\x7c\x65\x76\xee"
      "\xb5\xe9\x97\x66\xe7\xaf\xbd\xd8\xf4\x4c\x05\x1c\x97\x7e\xb2\xf9\xd8\x67"
      "\x67\x3e\x3d\x77\x20\xff\x3f\x76\xea\xfc\x03\xa7\x57\x95\xff\xa7\xae\xac"
      "\x7c\x5f\x6d\xef\x74\x8e\xd0\xe1\xcd\x9b\x4e\x7e\x50\xc0\xc9\xba\xb3\x5e"
      "\x55\xf9\x9f\x7e\x7e\xf1\x81\x1c\x35\xff\xc0\xa9\x21\xff\xd0\x5e\xf2\x0f"
      "\xed\x25\xff\xd0\x5e\xf2\x0f\xed\x25\xff\xd0\x5e\xf2\x0f\xed\x25\xff\xd0"
      "\x5e\xf2\x0f\xed\x25\xff\xd0\x5e\xfb\xf3\x0f\x00\xb4\xcb\xe0\x4c\xd3\x4f"
      "\x20\x03\x4d\x69\x7a\xfe\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x0e\x5b\x9e\x5a\xbf\xba\xb7\x4c\xaa\xe6\x17\xef\x25\xdb\x8f"
      "\x26\xe9\x8e\xaa\xdf\x19\xfe\x1f\x71\x72\xe3\xf0\xf5\xec\xaf\x45\xd5\xec"
      "\x2f\x45\xdd\x6d\x2c\xcf\xdd\x3d\xe6\x01\xc6\xf4\x51\xc3\x4f\x5f\xdf\xfc"
      "\x43\xb3\xf5\xbf\xbc\xab\xd9\xfa\x8b\xd7\x92\xa5\x37\x92\x5c\xe8\x76\x0f"
      "\xdf\x7f\xc5\xee\xfd\xf7\xff\xdd\xf2\x2f\x9f\xf7\x5e\x18\xb3\xc0\x7f\x54"
      "\x1c\xd8\x7f\xe4\xe9\xc9\xd6\x3f\xe8\x8f\x95\x66\xeb\x5f\xda\x48\x3e\xaf"
      "\xe6\x9f\x0b\xa3\xe6\x9f\x32\xb7\x0f\xd7\xa3\xe7\x9f\x7e\x75\xfd\xc6\xac"
      "\xff\xea\xef\x63\x1e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x89\xf9\x33"
      "\x00\x00\xff\xff\x69\xb7\x6d\xd8",
      584);
  syz_mount_image(/*fs=*/0x200000000000, /*dir=*/0x200000000280,
                  /*flags=MS_SYNCHRONOUS*/ 0x10, /*opts=*/0x200000000080,
                  /*chdir=*/-1, /*size=*/0x248, /*img=*/0x200000000780);
  syscall(__NR_open, /*file=*/0ul, /*flags=O_CREAT*/ 0x40ul, /*mode=*/0ul);
  memcpy((void*)0x200000000000,
         "lo\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 16);
  res = syscall(__NR_ioctl, /*fd=*/r[5], /*cmd=*/0x8933,
                /*arg=*/0x200000000000ul);
  if (res != -1)
    r[6] = *(uint32_t*)0x200000000010;
  *(uint16_t*)0x200000000580 = 0x11;
  *(uint16_t*)0x200000000582 = htobe16(0);
  *(uint32_t*)0x200000000584 = r[6];
  *(uint16_t*)0x200000000588 = 1;
  *(uint8_t*)0x20000000058a = 0;
  *(uint8_t*)0x20000000058b = 6;
  memset((void*)0x20000000058c, 255, 6);
  memset((void*)0x200000000592, 0, 2);
  syscall(__NR_bind, /*fd=*/-1, /*addr=*/0x200000000580ul, /*addrlen=*/0x14ul);
  return 0;
}
